spring:
#  profiles:
#    active: peer1
  application:
    name: eureka-server
eureka:
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false
#---
#spring:
#  profiles: peer1
#eureka:
#  instance:
#    hostname: peer1
#  client:
#    service-url:
#      defaultZone: http://peer2:1112/eureka/
#server:
#  port: 1111
#
#
#---
#spring:
#  profiles: peer2
#eureka:
#  instance:
#    hostname: peer2
#  client:
#    service-url:
#      defaultZone: http://peer1:1111/eureka/
#server:
#  port: 1112